-- Ejecutar como propietario/admin de la base de datos.
-- Reemplazar CHANGE_ME_APP_PASSWORD antes de ejecutar.
-- Este script no debe reutilizar una contraseña real.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_roles
    WHERE rolname = 'jyr_app'
  ) THEN
    EXECUTE 'CREATE ROLE jyr_app LOGIN PASSWORD ''CHANGE_ME_APP_PASSWORD'' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS';
  ELSE
    EXECUTE 'ALTER ROLE jyr_app LOGIN PASSWORD ''CHANGE_ME_APP_PASSWORD'' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS';
  END IF;
END
$$;

DO $$
DECLARE
  target_db text := current_database();
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO jyr_app', target_db);
  EXECUTE 'GRANT USAGE ON SCHEMA public TO jyr_app';
  EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO jyr_app';
  EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO jyr_app';
  EXECUTE 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO jyr_app';
  EXECUTE 'GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO jyr_app';
END
$$;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO jyr_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO jyr_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO jyr_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT EXECUTE ON PROCEDURES TO jyr_app;
