-- Ejecutar como propietario/admin de la base de datos.
-- Reemplazar CHANGE_ME_APP_PASSWORD antes de ejecutar.

CREATE ROLE jyr_app LOGIN PASSWORD 'CHANGE_ME_APP_PASSWORD';

GRANT CONNECT ON DATABASE j_y_r_db TO jyr_app;
GRANT USAGE ON SCHEMA public TO jyr_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO jyr_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO jyr_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO jyr_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO jyr_app;
